"""Shared simulation and booking constants."""

P_WEIGHT = 0.6
S_WEIGHT = 0.4
D_SCALE = 100.0
P_MIN = 0.1
P_MAX = 0.9

POP_W = 0.7
STA_W = 0.3
ALIGN_BONUS = 5.0

STAMINA_MIN_BOOKABLE = 10
STAMINA_RECOVERY_PER_SHOW = 15

RIVALRY_LEVEL_CAP = 4
RIVALRY_BONUS = 0.25
BLOWOFF_BONUS = 0.5
COOLDOWN_PENALTY = 1.0
COOLDOWN_SHOWS = 6

STARTING_MONEY = 20000

BOOKING_PRICE_BASE = 100
BOOKING_PRICE_A = 10
BOOKING_PRICE_EXPONENT = 1.2

AUDIENCE_POP_MULTIPLIER = 20
AUDIENCE_ALIGN_BONUS = 200
AUDIENCE_RIVALRY_BONUS = 300
AUDIENCE_COOLDOWN_PENALTY = 400

GATE_RATE = 1
MERCH_RATE_MIN = 0.05
MERCH_RATE_MAX = 0.50
MERCH_RATE_LINEAR = 0.02
MERCH_RATE_QUAD = 0.01

ECONOMY_RNG_MIN = 0.8
ECONOMY_RNG_MAX = 1.2

SHOW_MATCH_COUNT = 3
PROMO_VARIANCE = 8
SHOW_SLOT_TYPES = ("match", "promo", "match", "promo", "match")
SHOW_SLOT_COUNT = len(SHOW_SLOT_TYPES)
