site_name: WrestleGM
site_description: Project documentation for WrestleGM
site_url: http://localhost/

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
  - mermaid2

nav:
  - Home: index.md
  - User Journey: user_journey.md
  - Simulation Rules: simulation_rules.md
  - Data Model: data_model.md
  - Architecture & Design: architecture_and_design_patterns.md
