"""Route identifiers for WrestleGM UI navigation."""

MAIN_MENU = "main_menu"
SAVE_SLOTS = "save_slots"
GAME_HUB = "game_hub"
BOOKING_HUB = "booking_hub"
ROSTER = "roster"
MATCH_BOOKING = "match_booking"
PROMO_BOOKING = "promo_booking"
SIMULATING = "simulating"
RESULTS = "results"
